sudo: required
language: cpp
compiler: gcc

python: 
  - "3.7"

before_install:
  - sudo apt-get -y install python3-pip python-dev
  - sudo pip3 install -U setuptools
  - sudo pip3 install -U virtualenvwrapper
  - python3 -V
  - pip3 -V

install:
  - pip3 install sympy
  
script:
  - g++ -std=c++11 main.cpp
  - ./a.out

