matrix:
  include:
    - language: cpp
      compiler: g++
      script: 
        - g++ -std=c++17 main.cpp
        - ./a.out
    - language: python
      python: 3.7
      script:
        - pip install sympy
    

